### ISSUE TITLE
Massive sound delay on Steam Deck

### ISSUE THREAD

**Issue by Hedwig7s** [vanilla-wiiu/vanilla#135]
While input and video have no notable delay (that I can notice anyway), there is a massive sound delay of upwards of 1 second
Easiest way to test is within the Wii U menu switch between games in the menu
Likely a decoding or buffering issue as the delay is constant for the most part

**Comment by EMREOYUN** [comment]
This issue also happened while I was testing Arch Linux but I couldn't replicate it on Ubuntu 24.

**Comment by janerjak** [comment]
This was on first connect for me as well, but fixed itself after reconnecting.

**Comment by itsmattkc** [comment]
Audio latency should be resolved as of 00f41e05462fb3cbcc41ea08a2fa3828c6c36ada

**Comment by ZTylerDurden** [comment]
It was improved but still present. Playing Wii U on the TV simultaneously with vanilla steam deck will make it apparent.
